databases:
  - name: budget-app
    databaseName: budget_app_cuol
    user: budget_app_cuol_user

services:
  - type: web
    name: budget-app-project
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget_app_cuol
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false