databases:
  - name: db-budget-app
    databaseName: db_budget_app_0ui2
    user: db_budget_app_0ui2_user

services:
  - type: web
    name: budget-app
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: db-budget-app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false